### ISSUE TITLE
Вопрос по DrinkableDirectory

### ISSUE THREAD

**Issue by AlekseyGlushenok** [xeops/respondent#1]
Привет.
Я немного опоздал, но все равно спрошу) Подумал над решением с `DrinkableDirecotry`.
Собственно вопрос 
* как она решает проблему ведь при новой имплементации `IDrinkable` нам все равно придется менять метод `boot` иначе он не попадет в директорию. 
* Мы ограничиваем создание обьектов иначе метод `display` будет отрабатывать с ошибкой т.к. данные будут дублироваться, получается что мы обязываем всех вытаскивать имплементации из `DrinkableDirectory`?
```
class DrinkableDirectory
{
    private static ?DrinkableDirectory $instance = null;

    private function __construct()
    {

    }
    public static function getInstance() : DrinkableDirectory
    {
        if(self::$instance === null)
        {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private array $collection = [];

    public function list()
    {
        return array_keys($this->collection);
    }

    public function push(IDrinkable $drinkable)
    {
         // либо можно саму $drinkable записать, но тогда нужен будет метод для получения конкретной реализации
        $this->collection[get_class($drinkable)] = true;
    }
}

abstract class BaseDrinkable implements  IDrinkable
{
    public function __construct()
    {
        DrinkableDirectory::getInstance()->push($this);
    }
}
```

так получится что мы не запрещаем создавать новые объекты через `new Cup()` и избегаем дублирования.

Это все касательно только кружек и стаканов было.

Сама идея с регистрацией сервисов в директории очень крутая, хотел еще узнать это паттерн какой-то(потому что я ничего похожего ни разу не видел) или это какая-то кастомная наработка. Действительно очень интересно как это можно применить. Как я себе могу это представить, то это может лежать внутри фабрики и в ней идет создание выбранного класса(либо предоставление уже существующего), но мне непонятно зачем создавать вообще все объекты только чтобы они зарегались в директории, если можно в той же фабрике на лету создать только то, что мы хотим использовать?

PS: Это наверное самое крутое собеседование из тех что у меня было и вопросы очень крутые, спасибо, жаль что не прошел(

**Comment by xeops** [comment]
Привет.
boot  в данном случае аналог объявления классов в Symfony в качестве сервисов.
https://symfony.com/doc/3.2/service_container.html#creating-configuring-services-in-the-container
 
Про дублирование. Да, в моем коде возможно дублирование, но для упрощения условий, подразумевается, что каждый пишет уникальный класс. Про конкретный паттерн не могу сказать
Фабрика в данном варианте хороша, но она не решает вопроса коллекционирования, она нужна чтобы создавать как раз объекты ( https://refactoring.guru/ru/design-patterns/factory-method )
 
P.S. спасибо за отзыв.  
>Четверг, 3 июня 2021, 16:46 +03:00 от Aleksey Glushenok ***@***.***>:
> 
> 
>Привет.
>Я немного опоздал, но все равно спрошу) Подумал над решением с DrinkableDirecotry.
>Собственно вопрос
>*  как она решает проблему ведь при новой имплементации IDrinkable нам все равно придется менять метод boot иначе он не попадет в директорию.
>*  Мы ограничиваем создание обьектов иначе метод display будет отрабатывать с ошибкой т.к. данные будут дублироваться, получается что мы обязываем всех вытаскивать имплементации из DrinkableDirectory?
>class DrinkableDirectory
>{
>    private static ?DrinkableDirectory $instance = null;
>
>    private function __construct()
>    {
>
>    }
>    public static function getInstance() : DrinkableDirectory
>    {
>        if(self::$instance === null)
>        {
>            self::$instance = new self();
>        }
>        return self::$instance;
>    }
>
>    private array $collection = [];
>
>    public function list()
>    {
>        return array_keys($this->collection);
>    }
>
>    public function push(IDrinkable $drinkable)
>    {
>         // либо можно саму $drinkable записать, но тогда нужен будет метод для получения конкретной реализации
>        $this->collection[get_class($drinkable)] = true;
>    }
>}
>
>abstract class BaseDrinkable implements  IDrinkable
>{
>    public function __construct()
>    {
>        DrinkableDirectory::getInstance()->push($this);
>    }
>}
>
>так получится что мы не запрещаем создавать новые объекты через new Cup() и избегаем дублирования.
>Это все касательно только кружек и стаканов было.
>Сама идея с регистрацией сервисов в директории очень крутая, хотел еще узнать это паттерн какой-то(потому что я ничего похожего ни разу не видел) или это какая-то кастомная наработка. Действительно очень интересно как это можно применить. Как я себе могу это представить, то это может лежать внутри фабрики и в ней идет создание выбранного класса(либо предоставление уже существующего), но мне непонятно зачем создавать вообще все объекты только чтобы они зарегались в директории, если можно в той же фабрике на лету создать только то, что мы хотим использовать?
>PS: Это наверное самое крутое собеседование из тех что у меня было и вопросы очень крутые, спасибо, жаль что не прошел(
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Здесь могла быть ваша реклама. С уважением, Алексей Генералов
